# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "08c38da86db4224e99393e130267421e"
application_url = "https://cycling-understood-resources-assistant.trycloudflare.com"
embedded = true
name = "theme-customization"
handle = "theme-customization-4"

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://cycling-understood-resources-assistant.trycloudflare.com/auth/callback",
  "https://cycling-understood-resources-assistant.trycloudflare.com/auth/shopify/callback",
  "https://cycling-understood-resources-assistant.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
