# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "da85bc38bd236557b41d9aaa1743e0fb"
application_url = "https://rehabilitation-cuba-tvs-routine.trycloudflare.com"
embedded = true
name = "js-kickah-designs"
handle = "js-kickah-designs"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://rehabilitation-cuba-tvs-routine.trycloudflare.com/auth/callback",
  "https://rehabilitation-cuba-tvs-routine.trycloudflare.com/auth/shopify/callback",
  "https://rehabilitation-cuba-tvs-routine.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
